apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-java-app
  labels:
    app: tomcat-java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat-java-app
  template:
    metadata:
      labels:
        app: tomcat-java-app
    spec:
      containers:
        - name: myrepo
          image: 983426484039.dkr.ecr.ap-south-1.amazonaws.com/myrepo:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
